# Generated by Django 6.0 on 2025-12-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attr_dex', models.PositiveSmallIntegerField(default=1)),
                ('attr_stam', models.PositiveSmallIntegerField(default=1)),
                ('attr_str', models.PositiveSmallIntegerField(default=1)),
                ('attr_app', models.PositiveSmallIntegerField(default=1)),
                ('attr_cha', models.PositiveSmallIntegerField(default=1)),
                ('attr_manip', models.PositiveSmallIntegerField(default=1)),
                ('attr_per', models.PositiveSmallIntegerField(default=1)),
                ('attr_int', models.PositiveSmallIntegerField(default=1)),
                ('attr_wits', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=20)),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('caste_or_favored', models.BooleanField(default=0)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.character')),
            ],
        ),
        migrations.CreateModel(
            name='Intimacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intimacy', models.TextField(max_length=200)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.character')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.TextField(max_length=20)),
                ('ability_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.ability')),
            ],
        ),
    ]
